
#skill categories

TRADESKILLS = c("ELECTRICAL", "MECHANICS", "AUTO MECHANICS", "CARPENTRY", "CONSTRUCTION", 
                "CRANE OPERATOR", "PLUMBING", "RIGGING",
                "CRANE OPERATOR", "BOILER MAKER", "BOILER MAKING",
                "GAS DRILLING OPERATIONS", "ADVANCE DRIVING", "TRUCK DRIVING",
                "FITTING&TUNNING", "ROPE ACCESS TECHNICIAN", "RIGGING", "WELDING",
                "ROPE ACCESS TECHNICIAN", "AIR ON AND REFRIGERATION")

BUSINESS_SKILLS = c("ENTREPRENEURSHIP (RUNNING YOUR OWN BUSINESS)",
                    "BUSINESS COMMUNICATION", "BUSINESS MANAGEMENT", "BUSINESS STRATEGY",
                    "BUSINESS STUDIES", "FINANCIAL ACCOUNTING", "HR MANAGEMENT",
                    "PROPERTY DEVELOPMENT", "PROJECT MANAGEMENT", 
                    "ACCOUNTING", "MBA", "FLEET MANAGEMENT",
                    "ENTREPRENEURSHIP", "SALES", "SUPPLY CHAIN", "LOGISTIC")

IT_SKILLS = c("BASIC COMPUTER LITERACY", "IT", "IT FIXING COMPUTERS",
              "WEB DEVELOPMENT", "DATA ANALYSIS", "DATA ENGINEERING",
              "DATA SCIENCE",  "PROGRAMMING", 
              "CISCO", "CODING", "CYBER SECURITY", "APP DEVELOPMENT")

MARKETING = c("MARKETING", "MEDIA AND COMMUNICATION")

HIGH_SCHOOL = c("COMPLITING MATRIC", "MATRIC")

EDUCATION = c("EDUCATION", "TEACHING")

ENGINEERING = c("ENGINEERING", "ELECTRICAL ENGINEERING", "MILLWRIGHT ENGINEERING",
                "MECHANICAL ENGINEERING", "MECHANICAL ENGINEER")

HEALTH = c("HEALTH - PARAMEDICS", "HEALTH AND SAFETY MANAGEMENT", 
           "PSYCHOLOGY", "NURSING", "MEDICINE")

TOURISM = c("TOURISM", "TOURISM MANAGEMENT", "TRAVEL AND TOURISM")

CREATIVE = c("ACTING", "MULTIMEDIA", "MUSIC COMPOSITION AND PRODUCTION", 
             "MUSIC PERFORMANCE: COVERS PRODUCTION","SOUND ENGINEERING", 
             "PHOTOGRAPHY", "GRAPHIC DESIGN")

LAW_POLITICS = c("POLITICS", "PARALEGAL", "LAW", "BA IN INTERNATIONAL RELATIONS")

ENGLISH = "ENGLISH"
AGRICULTURE = c("AGRICULTURE", "AGRICULTURE EXTENSION")

OTHER = c("ARCHITECTURE", "BIOGRAPHY TESTING LEVEL 1", "NATURE CONSERVATION",
          "PRIVATE INVESTIGATION", "THEOLOGY")